# Generated by Django 4.0 on 2021-12-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='Ticket', max_length=55)),
                ('description', models.TextField(default='Another BE ticket')),
                ('points', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
