version: "3"

services:

  nginx:
    image: nginx:1.21-alpine
    restart: always
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - static_volume:/home/street_food/web/staticfiles
      - media_volume:/home/street_food/web/mediafiles
    ports:
      - 8000:80
    depends_on:
      - web

  web:
    image: lieberpaul/tickets:latest
    entrypoint: ["sh", "/home/street_food/web/entrypoint.dev.sh"]
    command: gunicorn street_food_project.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/street_food/web/staticfiles
      - media_volume:/home/street_food/web/mediafiles
    depends_on:
      - db
      - db_nosql
      - redis

  db:
    environment:
      - POSTGRES_USER=street_food_dev
      - POSTGRES_PASSWORD=street_food_dev
      - POSTGRES_DB=street_food_dev
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  db_nosql:
    image: mongo:4.4.11-focal
    environment:
      - MONGO_INITDB_ROOT_USERNAME=street_food_dev
      - MONGO_INITDB_ROOT_PASSWORD=street_food_dev
    restart: always
    volumes:
      - mongo_data:/var/lib/mongodb/data/

  redis:
    image: redis:6.0-alpine3.14

  celery:
    image: lieberpaul/tickets:latest
    restart: always
    entrypoint: ["sh", "/home/street_food/web/entrypoint.celery.sh"]


  celery_beat:
    image: lieberpaul/tickets:latest
    restart: always
    entrypoint: ["sh", "/home/street_food/web/entrypoint.celery-beat.sh"]

volumes:
  postgres_data:
  mongo_data:
  static_volume:
  media_volume:
