version: "3"

services:

  nginx:
    image: nginx:1.21-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx_dev:/etc/nginx/conf.d
      - static_volume:/home/street_food/web/staticfiles
      - media_volume:/home/street_food/web/mediafiles
    ports:
      - 8000:80
    depends_on:
      - web

  web:
    image: lieberpaul/tickets:latest
    volumes:
      - static_volume:/home/street_food/web/staticfiles
      - media_volume:/home/street_food/web/mediafiles
    expose:
      - 8000
    depends_on:
      - db
      - db_nosql

  db:
    environment:
      - POSTGRES_USER=street_food_dev
      - POSTGRES_PASSWORD=street_food_dev
      - POSTGRES_DB=street_food_dev
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  db_nosql:
    image: mongo:4.4.11-focal
    environment:
      - MONGO_INITDB_ROOT_USERNAME=street_food_dev
      - MONGO_INITDB_ROOT_PASSWORD=street_food_dev
    restart: always
    volumes:
      - mongo_data:/var/lib/mongodb/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080

volumes:
  postgres_data:
  mongo_data:
  static_volume:
  media_volume:
